repos:
  # -   repo: https://github.com/pre-commit/pre-commit-hooks
  #     rev: v4.4.0
  #     hooks:
  #     -   id: trailing-whitespace
  #     -   id: end-of-file-fixer
  #     #-   id: check-yaml
  #     -   id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  # -   repo: https://github.com/charliermarsh/ruff-pre-commit
  #     rev: 'v0.0.262'
  #     hooks:
  #     -   id: ruff
  #         args: [--fix, --exit-zero]

  # -   repo: https://github.com/pycqa/isort
  #     rev: 5.12.0
  #     hooks:
  #     -   id: isort

  # -   repo: https://github.com/pre-commit/mirrors-mypy
  #     rev: v1.3.0
  #     hooks:
  #     -   id: mypy
  #         additional_dependencies: [types-PyYAML]

  # -   repo: https://github.com/pycqa/flake8
  #     rev: 6.0.0
  #     hooks:
  #     -   id: flake8
  #         additional_dependencies:
  #             - flake8-docstrings
  #             - flake8-bugbear

  - repo: https://github.com/pycqa/pylint
    rev: v3.3.4
    hooks:
      - id: pylint
# -   repo: https://github.com/google/pyink
#     rev: '24.10.1'
#     hooks:
#     -   id: pyink
