---
name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"

      - name: Run tests
        run: python -m pytest

  run-action:
    name: Test Action
    runs-on: ubuntu-latest
    steps:
      # required because action is unpublished
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure login using Federated Credentials
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Test local action
        uses: ./
        with:
          azure-aiproject-connection-string: "eastus2.api.azureml.ms;040c3674-68d4-431e-b456-a8542c77b8d1;rg-aprilk-ai-agent-test-01b;ai-project-56uji2dklqysk"
          deployment-name: "gpt-4o-mini"
          data-path: ${{ github.workspace }}/samples/data/dataset-tiny.json
          agent-ids: "asst_qLmkrF8NEhh3HDhky8nWRVDk,asst_MSuB3GboqgJNw74ogzHDD2cQ"
