---
name: Test Local Action
on:
  workflow_dispatch:
    inputs:
      data_file:
        description: "Data file"
        required: false
        default: "dataset-tiny.json"
        type: choice
        options:
          - "dataset-tiny.json"
          - "dataset.json"
      compare_view:
        description: "Compare AI Agents?"
        required: false
        default: "true"
        type: boolean

permissions:
  id-token: write
  contents: read

jobs:
  run-action:
    runs-on: ubuntu-latest

    steps:
      # required because action is unpublished
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Azure login using Federated Credentials
        uses: azure/login@7184910d9eb2b1c5e48f7073824a90609bb9b6d6 # v2.3.1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Test local action
        uses: ./
        with:
          azure-ai-project-endpoint: "https://aoai-qyrftgva6obps.services.ai.azure.com/api/projects/proj-qyrftgva6obps"
          deployment-name: "gpt-4o-mini"
          data-path: ${{ github.workspace }}/samples/data/${{ github.event.inputs.data_file || 'dataset-tiny.json' }}
          agent-ids: ${{ github.event.inputs.compare_view == 'true' && 'agentv2test:12,agentv2test:13,agentv2test:14' || 'agentv2test:14' }}
